### PR TITLE
updated deps

### PR DESCRIPTION
**Pull request by cryogenian**

### CODE REVIEW

**Comment by garyb** [comment]
:+1: thanks, I've been meaning to do this for a while.

**Comment by joneshf** [comment]
You don't have to modify the bower version by hand. The gulp tasks take care of that. It actually gets out of sync if you modify them by hand. 

More importantly, I don't believe this can be a patch version. The dependencies have breaking changes with minor version bumps. So it'll cause issues down the line if this doesn't bump the minor rather than the patch. 

In any case, if you just revert the bower version change, then the tasks can take care of the rest.

**Comment by cryogenian** [comment]
changed to `0.7.0`

**Comment by joneshf** [comment]
Thanks!

**Pull request closed without merging**
