### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by garyb** [comment]
For release as `v0.5.0` due to backwards incompatible version bumping.

**Comment by garyb** [comment]
@joneshf to review, I guess?

**Comment by jdegoes** [comment]
I think this library is deprecated (??), @joneshf split up lenses into several smaller libraries with a slightly different organization.

**Comment by joneshf** [comment]
Nothing has been deprecated.

I'll release a new version in a minute.

**Comment by garyb** [comment]
Cool, just wanted to check changing those dependencies from your version of profunctors and distributive was ok :)

**Comment by joneshf** [comment]
Yeah, they were just interim versions so this would compile while the PR's went through for those libraries.

**Comment by joneshf** [comment]
Thanks!

**Pull request merged**
