### PR TITLE
updates for compiler version 0.12

### PR DESCRIPTION
**Pull request by Thimoteus**

### CODE REVIEW

**Comment by joneshf** [comment]
The build is failing because the PS version is still 0.11.x. The `package.json` will also need to be updated.

**Comment by iAmMrinal0** [comment]
Can a build be triggered again? It seems to build and tests seem to pass too.

**Comment by thomashoneyman** [comment]
Looks like the node version in Travis is too old and doesn't support the spread `...` operator. That will need to be bumped as well, I believe.

**Comment by iAmMrinal0** [comment]
Can I send a separate PR that updates the node version to 8 in travis so that this can be merged?

**Comment by thomashoneyman** [comment]
@joneshf I'll merge this by end of day today unless you have any objections. Thanks for the work, @Thimoteus, and the reminder @iAmMrinal0!

**Comment by joneshf** [comment]
No objections. Thanks for taking care of this!

**Comment by thomashoneyman** [comment]
Merged and released!

**Pull request merged**
