### PR TITLE
Updates for 0.7

### PR DESCRIPTION
**Pull request by paf31**
@joneshf Could you please review this? Also, what do you think about moving to Pulp for the build?

### CODE REVIEW

**Comment by paf31** [comment]
I still need to port the examples.

**Comment by paf31** [comment]
The examples seemed broken and used some stuff from `-index` etc., but I created a small test module out of the `Nested` example, which was the easiest one to get running (for me).

**Comment by joneshf** [comment]
Thanks!

I've not looked at pulp for quite a while. Does it support running user defined commands, and watching files? If I'd still need something like grunt/gulp/make for that I'd rather just stick to one build system.

Yeah, I think those examples rotted. Which reminds me that I wanted to have travis running for this thing.

**Comment by paf31** [comment]
In the core libraries, we've started using `pulp build` etc. as `npm` scripts, but I'm not sure if that supports `watch` or not.

When this is ready, could you please make a release? I'd like to update `thermite-todomvc` which uses `lens`.

Also, you might like to add the library to [Pursuit 2](http://new-pursuit.purescript.org) (I might send another PR soon to add some markdown comments if that's ok).

**Pull request merged**
